name: Build and Deploy to Cloud Run


on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]


jobs:
  build-and-deploy:
    name: Build and Deploy
    runs-on: ubuntu-latest
    permissions:
      contents: 'read'
      id-token: 'write'


    steps:
      - uses: actions/checkout@v4


      - name: Set up JDK 21
        uses: actions/setup-java@v3
        with:
          java-version: '21'
          distribution: 'temurin'

      - name: Setup Gradle
        uses: gradle/gradle-build-action@v2
        with:
          gradle-version: '9.0.0'


      - name: Google Auth
        id: auth
        uses: google-github-actions/auth@v1
        with:
          workload_identity_provider: 'projects/578301564702/locations/global/workloadIdentityPools/farmatodo-actions-pool/providers/github-provider'
          service_account: 'github-actions-builder@farmatodo-cicd-project.iam.gserviceaccount.com'


      - name: Set up Cloud SDK
        uses: google-github-actions/setup-gcloud@v1


      - name: Build with Gradle
        run: ./gradlew build


      - name: Build and Push Container
        run: |-
          gcloud builds submit \
            --config=cloudbuild.yml \
            --substitutions=_PROJECT_ID=${{ vars.PROJECT_ID || 'farmatodo-cicd-project' }}



