server:
  port: 8080

spring:
  application:
    name: "PruebaTecnicaJava"
  devtools:
    add-properties: false

  r2dbc:
    url: r2dbc:h2:mem:///testdb;DB_CLOSE_DELAY=-1
    username: sa
    password: ""

  sql:
    init:
      mode: always
      schema-locations: classpath:db/schema.sql

  h2:
    console:
      enabled: false
      path: /h2

management:
  endpoints:
    web:
      exposure:
        include: "health,prometheus"
  endpoint:
    health:
      probes:
        enabled: true

cors:
  allowed-origins: ${ALLOWED_ORIGINS:http://localhost:4200,http://localhost:8080}

tokenization:
  rejection-probability: ${REJECTION_PROBABILITY:0.2}

security:
  api-key: ${SECURITY_API_KEY:farmatodo-secret-key-2024}

products:
  search:
    min-stock: ${PRODUCTS_MIN_STOCK:5}

logging:
  level:
    io.r2dbc.h2: ERROR

---
spring:
  config:
    activate:
      on-profile: local
  h2:
    console:
      enabled: true

---
spring:
  config:
    activate:
      on-profile: dev
  h2:
    console:
      enabled: false
logging:
  level:
    root: INFO

---
spring:
  config:
    activate:
      on-profile: prod
  h2:
    console:
      enabled: false
logging:
  level:
    root: INFO



