FROM eclipse-temurin:21-jdk-alpine
RUN adduser -D -u 1001 appuser
VOLUME /tmp
COPY applications/app-service/build/libs/PruebaTecnicaJava.jar PruebaTecnicaJava.jar
ENV JAVA_OPTS="-XX:+UseContainerSupport -XX:MaxRAMPercentage=70 -Djava.security.egd=file:/dev/./urandom"
USER appuser
ENTRYPOINT [ "sh", "-c", "java $JAVA_OPTS  -jar PruebaTecnicaJava.jar" ]
